language: generic

script:
  - if [ "$TRAVIS_BRANCH" = "dev" ]; then ./gradlew buildDev; fi
install:
  - nvm use 11.0.0
  - npm --version
  - node --version
  - ./gradlew build
#  - git clone https://github.com/ParNote-App/ParNote-UI.git parnote-ui
#  - cd parnote-ui
#  - npm install
#  - npm run build
#  - ls -a
#  - ls ..
#  - cp -avr public ../public
#  - cd ..
#  - rm -rf parnote-ui
#  - ls -a
#  - ls -a public
before_deploy:
  - git config --local user.name $GITHUB_USERNAME
  - git config --local user.email $GITHUB_EMAIL
  - export TRAVIS_TAG=${TRAVIS_TAG:-$(date +'%Y%m%d%H%M%S')-$(git log --format=%h -1)}
  - git tag $TRAVIS_TAG

deploy:
  - provider: heroku
    skip_cleanup: true
    api_key: $HEROKU_API_KEY
    strategy: api
    app: parnote
    on:
      branch: master
  - provider: releases
    api_key: $GITHUB_API_KEY
    file: "ParNote-1.0-all.jar"
    on:
      branch: dev
    skip_cleanup: 'true'
    prerelease: "true"