version: '3'
services:
  db:
    image: mariadb:latest
    command: [ "--character-set-server=utf8", "--collation-server=utf8_unicode_ci" ,"--default-authentication-plugin=mysql_native_password" ]
    restart: always
    environment:
      MYSQL_DATABASE: parnote
      MYSQL_ROOT_PASSWORD: parnote
    ports:
      - "3306:3306"
    volumes:
      - .docker/datababase:/var/lib/mysql
