package com.parnote

enum class ErrorCode {
    UNKNOWN_ERROR,
    UNKNOWN_ERROR_2,
    UNKNOWN_ERROR_3,
    UNKNOWN_ERROR_4,
    UNKNOWN_ERROR_5,
    UNKNOWN_ERROR_6,
    UNKNOWN_ERROR_7,
    UNKNOWN_ERROR_8,
    UNKNOWN_ERROR_9,

    REGISTER_EMAIL_INVALID,
    REGISTER_USERNAME_EMPTY,
    REGISTER_USERNAME_LONG,
    REGISTER_USERNAME_SHORT,
    REGISTER_USERNAME_INVALID,
    REGISTER_NOT_ACCEPTED_TERMS,

    RESET_PASSWORD_USERNAME_OR_EMAIL_INVALID,
    RESET_PASSWORD_RECAPTCHA_INVALID,
    RESET_PASSWORD_USER_NOT_EXISTS,

    EMAIL_VERIFICATION_INVALID_TOKEN,
}