package com.parnote

// last ID 0
enum class ErrorCode {
    SCHEME_VERSION_ADD_ERROR,
    UNKNOWN_ERROR,

    REGISTER_NAME_SHORT,
    REGISTER_NAME_LONG,
    REGISTER_SURNAME_SHORT,
    REGISTER_SURNAME_LONG,
    REGISTER_NAME_SURNAME_INVALID,
    REGISTER_EMAIL_INVALID,
    REGISTER_USERNAME_EMPTY,
    REGISTER_USERNAME_LONG,
    REGISTER_USERNAME_SHORT,
    REGISTER_USERNAME_INVALID,
    REGISTER_PASSWORD_INVALID,
    REGISTER_NOT_ACCEPTED_TERMS


}